### PR TITLE
Fix ClassNotFoundException in repl after a build

### LINKED ISSUE #812: ClassNotFoundException in etlas repl after etlas build
* If you do a `etlas clean && etlas build && etlas repl` and then try to evaluate a function from some package module it throws an error. F.e. with wai-servlet-handler-jetty:
```
Prelude Network.Wai.Servlet.Examples Network.Wai.Servlet.Handler.Jetty> run 3000 appSimple
*** Exception: java.lang.RuntimeException: Failed during evalStmt of Eta REPL expression
        at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:253)
        at eta.serv.Utils.evalStmt(Utils.java:32)
        at eta_serv.eta.serv.Run$sat$21.applyV(Run.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:131)
        at eta_serv.eta.serv.Run$sat$20.applyV(Run.hs)
        at eta_serv.eta.serv.Run.$La4$1(Run.hs)
        at eta_serv.eta.serv.Run$sat$23.applyV(Run.hs)
        at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:93)
        at eta_serv.eta.serv.Run$sat$19.applyV(Run.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:131)
        at eta_serv.eta.serv.Run$sat$18.applyV(Run.hs)
        at eta.runtime.stg.Closures$EvalLazyIO.enter(Closures.java:108)
        at eta.runtime.stg.Capability.schedule(Capability.java:183)
        at eta.runtime.concurrent.WorkerThread.run(WorkerThread.java:16)
Caused by: java.lang.RuntimeException: Failed during evalIOInternal of Eta REPL expression
        at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:381)
        at eta.serv.REPLClassLoader.evalStmt(REPLClassLoader.java:246)
        ... 13 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at eta.serv.REPLClassLoader.evalIOInternal(REPLClassLoader.java:379)
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: wai_servlet_handler_jetty/network/wai/servlet/handler/Jetty
        at interactive.EtaRepl1_3$sat$3.thunkEnter(Interactive.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at base.ghc.Base.id(Base.hs:964)
        at base.ghc.Base$id.apply1(Base.hs:964)
        at interactive.EtaRepl1_3$sat$2.thunkEnter(Interactive.hs)
        at eta.runtime.thunk.UpdatableThunk.evaluate(UpdatableThunk.java:19)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:120)
        at base.ghc.Base.bindIO1(Base.hs)
        at base.ghc.Base.bindIO(Base.hs:1067)
        at base.ghc.Base$bindIO.apply2V(Base.hs:1067)
        at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:64)
        at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:112)
        at eta.runtime.thunk.Thunk.applyV(Thunk.java:120)
        at eta.runtime.exception.Exception.unmaskAsyncExceptions(Exception.java:93)
        at base.control.exception.Base$sat$25.applyV(Base.hs)
        at eta.runtime.exception.Exception.catch_(Exception.java:131)
        at base.control.exception.Base$sat$22.applyV(Base.hs:262)
        at eta.runtime.exception.Exception.maskAsyncExceptions(Exception.java:44)
        at base.control.exception.Base.bracket1(Base.hs:264)
        at base.system.Environment.withArgs1(Environment.hs)
        at base.system.Environment.withArgs(Environment.hs:150)
        at base.system.Environment$withArgs.apply2V(Environment.hs:150)
        at eta.runtime.apply.PAPSlow.apply(PAPSlow.java:64)
        at eta.runtime.apply.PAPSlow.applyV(PAPSlow.java:112)
        at eta.runtime.stg.Closures$EvalIO.enter(Closures.java:133)
        at eta.runtime.stg.Capability.schedule(Capability.java:183)
        at eta.runtime.stg.Capability.scheduleClosure(Capability.java:123)
        at eta.runtime.Runtime.evalIO(Runtime.java:358)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: wai_servlet_handler_jetty.network.wai.servlet.handler.Jetty
        at java.net.URLClassLoader.findClass(Unknown Source)
        at eta.serv.REPLClassLoader$ChildREPLClassLoader.loadClass(REPLClassLoader.java:69)
        ... 47 more
```
* If you do `etlas clean && etlas repl` the error is not thrown

### PR DESCRIPTION
**Pull request by jneira**
Fixes #812
## Description

Add some traces to REPL and load the module jar when the source has not changed and eta doesnt compile it again
## How Has This Been Tested?

Manually in a simple project and inspecting traces
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change
- [ ] Test suite change

## Checklist:

- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: compiler/Eta/Main/DriverPipeline.hs [hunk 1]
```diff
@@ -219,6 +220,8 @@ compileOne' m_tc_result mHscMessage
                     hm_details = details,
                     hm_iface = iface,
                     hm_linkable = maybe_old_linkable }
+            when (hsc_lang == HscInterpreted) $
+              addModuleClassPath hsc_env (concatMap linkableObjs (maybeToList maybe_old_linkable))
```
Comment (rahulmutt) [inline compiler/Eta/Main/DriverPipeline.hs]: If I'm reading this correctly - `addModuleClassPath` will get called for every module that is being compiled when interepreted mode is going on. Perhaps a more efficient way to get it done is here: https://github.com/typelead/eta/blob/57ec8b168375c64abbec1fa65c15a3a912142cd5/compiler/Eta/REPL/Linker.hs#L309

Comment (jneira) [reply compiler/Eta/Main/DriverPipeline.hs]: Mmm you mean using the function `linkClasses`? Sorry if if missing something obvious, how would improve the loading?

**Comment by jneira** [comment]
I've tested two sequences (complete):
* clean -> repl
* clean -> build -> repl
I will test a half build too as you suggested.

File: compiler/Eta/Main/DriverPipeline.hs (hunk 1 above)
Comment (rahulmutt) [reply compiler/Eta/Main/DriverPipeline.hs]: Improving in the sense that you reduce the number of calls to `eta-serv`. If you do it inside of `unload_wkr`, which gets called once per build (regardless of the number of modules) and it will be a lot more efficient.

Comment (jneira) [reply compiler/Eta/Main/DriverPipeline.hs]: Ok, so the idea is accumulate the non compiled modules and call iserv just one time with all the classes/jars of all, right?
Actually the `unload` action is called with `keep_linkables` empty, although the modules are not been recompiled. I get no way to trigger a call with some info in that param.
I've added some more traces to check it. 
So we should add some code in [`GHCMake`](https://github.com/typelead/eta/blob/57ec8b168375c64abbec1fa65c15a3a912142cd5/compiler/Eta/Main/GhcMake.hs#L309) to add those modules "up-to-date" to the call to `unload`, right?

Comment (jneira) [reply compiler/Eta/Main/DriverPipeline.hs]: However, in the traces from build+repl i see:
```
Stable obj: [$37V :-> Primes, $37Z :-> Main]
Stable BCO: []
Unload old objects
Keeping linkables:  []
Adding module classpath: []
```
So in this code from GHCMake: 
```haskell
liftIO $ debugTraceMsg dflags 2 (text "Stable obj:" <+> ppr stable_obj $$
                            text "Stable BCO:" <+> ppr stable_bco)

    -- Unload any modules which are going to be re-linked this time around.
    let stable_linkables = [ linkable
                           | m <- nonDetEltsUniqSet stable_obj ++
                                  nonDetEltsUniqSet stable_bco,
                             -- It's OK to use nonDetEltsUniqSet here
                             -- because it only affects linking. Besides
                             -- this list only serves as a poor man's set.
                             Just hmi <- [lookupHpt pruned_hpt m],
                             Just linkable <- [hm_linkable hmi] ]
    liftIO $ unload hsc_env stable_linkables
```
`lookupHpt pruned_hpt` is returning []?

Comment (jneira) [reply compiler/Eta/Main/DriverPipeline.hs]: @rahulmutt maybe we can left the optimization for later
I was thinking taht maybe we could load all stable modules?

Comment (rahulmutt) [reply compiler/Eta/Main/DriverPipeline.hs]: Yes, that's what I was thinking as well, but it looks like something's amiss in the stable module calculations since it's showing `Keeping linkables: []`.
